image:
  tag: v1.29.6

extraEnvVars:
- name: TZ
  value: Asia/Seoul

service:
  http:
    type: ClusterIP
    port: 80
  smtp:
    type: ClusterIP
    port: 25

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: mailpit.cnapcloud.com
  path: /
  pathType: Prefix

mailpit:
  smtp:
    authFile:
      enabled: true
      existingSecret:
        name: mailpit-smtp-auth
        keyMapping:
          smtp.htpasswd: smtp.htpasswd

persistence:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
