apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

generators:
  - ./helm/helm-chart.yaml

resources:
- ../../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: minio-root-secret
    envs:
      - ./secrets/minio-root-secret.env
