{{- range .Values.roles }}
{{- $secret := index $.Values.secrets .secretName | default dict }}
{{- if $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ $secret.username | quote }}
  password: {{ $secret.password | quote }}
---
{{- end }}
{{- end }}
