apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: qdrant
name: qdrant
chartHome: ../../base/helm
chart: qdrant
releaseName: qdrant
valuesFile: ./helm/values-dev.yaml
includeCRDs: true
namespace: mlops