apiVersion: v1
kind: Secret
metadata:
  name: mailpit-smtp-auth
  namespace: infra
type: Opaque
stringData:
  smtp.htpasswd: "admin@cnapcloud.com:$2y$05$AJe6boDBxUW4aZK1S.DeSuy5i6Y4Wgy2JpcDi1QPlOpKS08W46R3W"
