apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-api.fullname" . }}
spec:
  selector:
    app: {{ include "rag-api.fullname" . }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
