# CloudNativePG Operator Chart Values
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    memory: 200Mi

# Prometheus 모니터링 및 Grafana 대시보드 설정
monitoring:
  podMonitorEnabled: true
  podMonitorAdditionalLabels: 
    release: prometheus
  grafanaDashboard:
    create: true
    configMapName: "cnpg-grafana-dashboard"
    labels:
      grafana-dashboard: "1"